services:
  traefik:
    image: "traefik:v3.4"
    container_name: "traefik"
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entryPoints.web.address=:80"
    ports:
      - "8081:80"       # HTTP
      - "8091:8080"   # Traefik Dashboard
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    networks:
      - onixnet

  db:
    image: postgres:17
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env
    networks:
      - onixnet
  django-web:
    build:
      context: .
      dockerfile: compose/production/Dockerfile
    container_name: django-docker
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.django.rule=PathPrefix(`/`)"
      - "traefik.http.routers.django.entrypoints=web"
      - "traefik.http.services.django.loadbalancer.server.port=8000"
    depends_on:
      - db
    environment:
      DJANGO_SECRET_KEY: ${DJANGO_SECRET_KEY}
      DEBUG: ${DEBUG}
      DJANGO_LOGLEVEL: ${DJANGO_LOGLEVEL}
      DJANGO_ALLOWED_HOSTS: ${DJANGO_ALLOWED_HOSTS}
      DATABASE_ENGINE: ${DATABASE_ENGINE}
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_USERNAME: ${DATABASE_USERNAME}

      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      DATABASE_HOST: ${DATABASE_HOST}
      DATABASE_PORT: ${DATABASE_PORT}
    env_file:
      - .env
    networks:
      - onixnet
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - media_data:/app/media
  redis:
    image: redis:7-alpine
    networks:
      - onixnet
    volumes:
      - production_redis_data:/data
  celery_worker:
    build:
      context: .
      dockerfile: ./compose/production/Dockerfile
    command: /start-celeryworker
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    env_file:
      - .env
    depends_on:
      - redis
      - db
    networks:
      - onixnet
  celery_beat:
    build:
      context: .
      dockerfile: ./compose/production/Dockerfile
    command: /start-celerybeat
    env_file:
      - .env
    depends_on:
      - redis
      - db
    networks:
      - onixnet
  flower:
    build:
      context: .
      dockerfile: ./compose/production/Dockerfile
    command: /start-flower
    env_file:
      - .env
    ports:
      - 5557:5555
    depends_on:
      - redis
      - db
    networks:
      - onixnet
volumes:
  postgres_data:
  production_redis_data:
  media_data:

networks:
  onixnet:
    driver: bridge