site_name: Onix Enviro Docs
site_url: https://onixtech.org/docs
theme:
  name: material
  logo: assets/logo.svg
  favicon: assets/logo.svg

nav:
  - Home: index.md
  - Getting Started:
      - Installation: getting-started/installation.md
      - Configuration: getting-started/configuration.md
  - Troubleshooting: troubleshooting/index.md