
FROM quay.io/jupyter/scipy-notebook:latest


EXPOSE 23000

CMD ["start-notebook.py", "--NotebookApp.token=''", "--NotebookApp.password=''", "--NotebookApp.port=23000", "--NotebookApp.allow_origin='*'"]