name: Build and Push Environment with docker image

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      packages: write
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.PAT_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3


      - name: Build lowercase image reference
        id: lower
        run: |
          echo "IMAGE_REF=ghcr.io/${GITHUB_REPOSITORY_OWNER,,}/enviro_dockerenv" >> $GITHUB_ENV

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: ./compose/docker_env  # Path to your Dockerfile
          file: ./compose/docker_env/Dockerfile
          push: true
          tags: ghcr.io/${{ env.IMAGE_REF }}/enviro_dockerenv:latest
